# Generated by Django 5.1.2 on 2024-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJtIrj6mXG4Dwt-eacKnB77UfKihG2cX05Zw&s', max_length=500),
        ),
    ]
